### ISSUE TITLE
Issue with Pledge input

### ISSUE THREAD

**Issue by opiumniy** [jam3scampbell/ProctorAI#12]
Windows app.
Python 3.12.4

When The system detects something that is irrelevant to the task it prompts me to enter the Pledge that I won't be doing that, however, the input is not accepted and it keeps returning "Incorrect input Please try again"

![2024-07-24_12-43-20](https://github.com/user-attachments/assets/1fd0a4c1-2884-4c40-9344-99037222f764)

**Comment by jam3scampbell** [comment]
It might've been that there was some extra whitespace in the pledge message suggested by the model. I just pushed a change that strips all extra whitespace. Lmk if that doesn't solve the problem.
