### ISSUE TITLE
Request for Windows Version

### ISSUE THREAD

**Issue by ZXX-Andrew** [jam3scampbell/ProctorAI#13]
I would like to request a Windows version of this program. Currently, the repository supports macOS, but having a Windows version would be extremely helpful for users who do not have access to a Mac. TAT...

Or is there any way to rewrite the scripts to make them compatible with Windows?   If there are specific challenges or requirements for this, please let us know.

Thank you for considering this request.

**Comment by jam3scampbell** [comment]
Check out the `windows` branch for now. At some point, I'll merge it into main.
